name: Build on Mac OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MacOS:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build COMiniSatPS
      run: |
        cd ..
        wget https://baldur.iti.kit.edu/sat-competition-2016/solvers/main/COMiniSatPSChandrasekharDRUP.z
        unzip COMiniSatPSChandrasekharDRUP.zip
        mv 'COMiniSatPS Chandrasekhar DRUP/cominisatps' .
        cd cominisatps
        patch -p1 <../UWrMaxSat/cominisatps.patch
    - name: make SAT solver library
      run: |
        cd ../cominisatps/simp
        MROOT=.. make libr
    - name: create SAT solver links
      run: |
        cd ../cominisatps
        mkdir minisat
        cd minisat
        ln -s ../core ../simp ../mtl ../utils .
    - name: build UWrMaxSat
      run: |
        make config
        MAXPRE= USESCIP= make r
